### ISSUE TITLE
Error when using storagepool

### ISSUE THREAD

**Issue by wangzhizheng** [emccode/puppet-vnx#1]
we have tested in two versions, PE3.8 and Puppet4.2
when using storagepool, we hit this error.

Error: Parameter disks failed on Vnx_storagepool[wangzz_pool]: Validate method failed for class disks: undefined method `all?' for "1_0_7":String at /home/wangzz/modules/wzz_test/manifests/init.pp:20

Looked into lib/puppet/type/vnx_storagepool.rb
edit "validate do |value|" to “validate do |*value|” can make it work properly.

**Comment by kacole2** [comment]
Thanks for the fix. We will have the appropriate party look into this. Please submit a PR if you would like to further contribute.

**Comment by grissomsh** [comment]
Thanks Zhizheng. Maybe you can fork the project, fix the bug and then submit a PR. Thus git will record your contribution, thanks.

**Comment by LaynePeng** [comment]
Close this issue cuz this pr from @wangzhizheng has been merged see #2. Thanks @wangzhizheng !
