### ISSUE TITLE
vnx_storagepool ensure -> present is not working properly

### ISSUE THREAD

**Issue by scottbri** [emccode/puppet-vnx#6]
I applied the attached manifest and created a storagepool and a couple of LUNs.  This was entirely successful.  I then re-applied the same manifest after a time.  The re-apply failed attempting to execute navisphere commands a second time.  In short, idempotency is broken for vnx_storagepool.

'''
puppet apply vnx.pp --verbose
Notice: Compiled catalog for lp01.vlab.local in environment production in 0.17 seconds
Info: Applying configuration version '1449629787'
Notice: /Stage[main]/Main/Vnx_storagepool[puppet-pool]/disks: disks changed [] to '0_0_9 0_0_10 0_0_11 0_0_12 0_0_13 1_1
_9 1_1_10 1_1_11 1_1_12 1_1_13'
Notice: /Stage[main]/Main/Vnx_storagepool[puppet-pool]/cancel_expand: defined 'cancel_expand' as 'false'
Error: /Stage[main]/Main/Vnx_storagepool[puppet-pool]: Could not evaluate: Command error, output:
The best practices check for the storagepool's expansion did not finish successfully. The storagepool will not be expand
ed
  Rule Messages
      Could not use the disk : 0_0_9. The disk is already part of a Storage Pool.
      Could not use the disk : 0_0_10. The disk is already part of a Storage Pool.
      Could not use the disk : 0_0_11. The disk is already part of a Storage Pool.
      Could not use the disk : 0_0_12. The disk is already part of a Storage Pool.
      Could not use the disk : 0_0_13. The disk is already part of a Storage Pool.
      Could not use the disk : 1_1_9. The disk is already part of a Storage Pool.
      Could not use the disk : 1_1_10. The disk is already part of a Storage Pool.
      Could not use the disk : 1_1_11. The disk is already part of a Storage Pool.
      Could not use the disk : 1_1_12. The disk is already part of a Storage Pool.
      Could not use the disk : 1_1_13. The disk is already part of a Storage Pool.

Notice: Finished catalog run in 24.94 seconds
'''

**Comment by scottbri** [comment]
the manifest in question:
'''
transport {'vnx5400':
  username => 'sysadmin',
  password => 'sysadmin',
  server   => '192.168.1.31',
  cli_path => '"C:\Program Files (x86)\EMC\Navisphere CLI\naviseccli.exe"'
}

vnx_storagepool {"puppet-pool":
  transport => Transport['vnx5400'],
  disks => ['0_0_9', '0_0_10', '0_0_11', '0_0_12', '0_0_13', '1_1_9', '1_1_10', '1_1_11', '1_1_12', '1_1_13'],
  raid_type => 'r_5',
  auto_tiering => 'scheduled',
  ensure_fastcache => 'true',
  ensure => present
}

vnx_lun {"sds01":
  transport => Transport['vnx5400'],
  pool_name => 'puppet-pool',
  type => 'thin',
  capacity => '10',
  size_qual => 'gb',
  initial_tier => 'highest_available',
  tiering_policy => 'auto_tier',
  auto_assign => 'true',
  ensure => present
}

vnx_lun {"sds02":
  transport => Transport['vnx5400'],
  pool_name => 'puppet-pool',
  type => 'thin',
  capacity => '10',
  size_qual => 'gb',
  initial_tier => 'highest_available',
  tiering_policy => 'auto_tier',
  auto_assign => 'true',
  ensure => present
}
'''

**Comment by scottbri** [comment]
I realized too, that I pulled the module from puppet forge, not from here.  There could be differences.

**Comment by swindlife** [comment]
Can you provide the version of the Navicli you used? It seems a problem that puppet failed to get the current disks of a storagepool and try to readd disks in use.

**Comment by scottbri** [comment]
agreed, current_properties[] doesn't contain any :disks data... 
I must admit that I'm running this in an EMC internal vlab... I expect this is a virtual vnx on the backend.  That said, all the naviseccli commands seem to be working fine, and the initial creation of the storagepool and LUNs work fine... it's just subsequent runs aren't picking up the current storage pool config.

@(#)Navisphere naviseccli Revision 7.33.8.1.19 on Thu Jul 23 23:03:13 2015
Copyright (C) 1997-2015, EMC Corporation

> naviseccli -User sysadmin -Password sysadmin -Scope 0 -Address 192.168.1.31 storagepool -list -name puppet-pool
> Pool Name:  puppet-pool
> Pool ID:  0
> Raid Type:  r_5
> Percent Full Threshold:  70
> Description:
> Disk Type:  Mixed
> State:  Ready
> Status:  OK(0x0)
> Current Operation:  None
> Current Operation State:  N/A
> Current Operation Status:  N/A
> Current Operation Percent Completed:  0
> Raw Capacity (Blocks):  209715200
> Raw Capacity (GBs):  100.000
> User Capacity (Blocks):  157593600
> User Capacity (GBs):  75.146
> Consumed Capacity (Blocks):  11031552
> Consumed Capacity (GBs):  5.260
> Available Capacity (Blocks):  146562048
> Available Capacity (GBs):  69.886
> Percent Full:  7.000
> Total Subscribed Capacity (Blocks):  11031552
> Total Subscribed Capacity (GBs):  5.260
> Percent Subscribed:  7.000
> Oversubscribed by (Blocks):  0
> Oversubscribed by (GBs):  0.000
> Disks:
> Bus 1 Enclosure 1 Disk 13
> Bus 0 Enclosure 0 Disk 9
> Bus 0 Enclosure 0 Disk 11
> Bus 0 Enclosure 0 Disk 12
> Bus 1 Enclosure 1 Disk 11
> Bus 1 Enclosure 1 Disk 9
> Bus 0 Enclosure 0 Disk 10
> Bus 1 Enclosure 1 Disk 12
> Bus 0 Enclosure 0 Disk 13
> Bus 1 Enclosure 1 Disk 10
> LUNs:
> <<--- no luns here is correct.  None were created at the time of execution

**Comment by swindlife** [comment]
I passed it successfully in my dev environment right now. I notice that you ran it on a Windows node, so I think it may be a problem about the ruby version or even Windows Command Line. I have to admitted that we haven't done much tests on Windows platform, and I suggest you to try it on a Linux server.

**Comment by scottbri** [comment]
so, am I correct that inside vnx_storagepool.rb -> set_storagepool current_properties[] contains the "real" state of the array, and resource[] contains puppets "to be" target state?

where are those arrays defined?  does puppet do it for you, and are those a standard global variable provided by the puppet?

**Comment by swindlife** [comment]
The current_properties[] get the current state of a resource through get_current_properties method. This is defined by myself, and you can see it in lib/puppet_x/puppetlabs/transport/emc_vnx.rb.

The resource[] contain the values which you defined in the manifest file. This is a standard global variable provided by Puppet.
